version: '3'
services:
  database:
    image: postgres:latest # use latest official postgres version
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - database.env # configure postgres
    volumes:
      - db:/var/lib/postgresql/data/ # persist data even if container shuts down

volumes:
  db:
    driver: local # named volumes can be managed easier using docker-compose