server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#  cloud:
#    gateway:
#      routes:
#        - id: employeeModule
#          uri: lb://FIRST-SERVICE
#          predicates:
#            - Path=/employee/**
#        - id: consumerModule
#          uri: lb://SECOND-SERVICE
#          predicates:
#            - Path=/consumer/**