spring:
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      ack-mode: manual_immediate
    producer:
      topic: topic-1p
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      acks: 1

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka