spring:
  application:
    name: backend-service-account

server:
  port: 8084
  servlet:
    context-path: /account
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
